### ISSUE TITLE
Feature request - Add URI and custom fields

### ISSUE THREAD

**Issue by phdelodder** [alex3305/home-assistant-addons#17]
I'm using zoneminder intgration and for that I defined 3 secrets: 
```yaml
zoneminder-host: URL
zoneminder-username: myuser
zoneminder-password: mypassword
```
If an URI is defined in a login, can de URI be added?

**Comment by alex3305** [comment]
Thanks for your feedback and using the Bitwarden secrets add-on.

In version 1.0.0 I intended that you choose your own field name by abusing the Bitwarden username field within an item. After some feedback on Reddit, I've noticed that several users wanted to use the Bitwarden Secrets add-on differently. Thus I've added the ability to use both the username and passwords fields. And set this behaviour as default.

I've noticed already that users want more fields they can use for their secrets. The URL field is a decent starting point, but also being able to utilize custom fields would be a great addition to this add-on.

Therefore, usage of the URL field is planned for release 1.2.0 and custom fields for 1.3.0. I have no ETA of these releases, but I want to resume work on the Bitwarden Secrets for Home Assistant ASAP.

**Comment by alex3305** [comment]
I've just released Bitwarden Secrets for Home Assistant version 1.2.0 (d7d5ca7bf0de80e6ef75e82ad0a48b5bb632dc35) with support for custom fields and URI's. When parsing an example/test Bitwarden Item it shows up as:

```yaml
test_username: 'test_username'
test_password: 'YaaJvG3fBaqEQ8'
test_notes: 'my_note'
test_uri_1: 'https://github.com'
test_uri_2: 'https://home-assistant.io'
test_custom_text: 'sZC7oAxZ52g8Hz'
test_custom_password: 'xZ4ribnfQTtE59'
test_custom_true: 'true'
test_custom_false: 'false'
```

It would be great if you can test this version and report your findings. Thanks again for using this add-on and your feedback.
