### ISSUE TITLE
Reload supervsior after secrets update

### ISSUE THREAD

**Issue by alex3305** [alex3305/home-assistant-addons#26]
The supervisor needs to be reloaded after the secrets have been updated.

**Comment by SVNKoch** [comment]
Workaround:
Weload the config everytime the addon stops.

<img src="https://user-images.githubusercontent.com/39488412/196908044-f849f4be-6f42-41fd-ae70-36e35c7f710d.png" width="350" />

```yaml
alias: Reload Secrets after Bitwarden Generation
description: ""
trigger:
  - type: not_running
    platform: device
    device_id: 1e8c808a37b6924dcd32b8f5275e07dd
    entity_id: binary_sensor.bitwarden_secrets_for_home_assistant_running
    domain: binary_sensor
condition: []
action:
  - service: homeassistant.reload_core_config
    data: {}
mode: single
```
_For this to work, the `Running` Sensor has to be enabled for this addon. Go to Settings > Devices > Bitwarden secrets for Home Assistant > Sensors > Running > Advanced Options > Enable_
