### ISSUE TITLE
Addon stops with a strange error on config files !

### ISSUE THREAD

**Issue by vincegre** [alex3305/home-assistant-addons#33]
Hi

Trying to run the addon following documentation but I have that problem:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Rclone
 Rclone is a command line program to sync files and directories to and from various providers.
-----------------------------------------------------------
 Add-on version: 3.0.8
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.0.rc1  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.4.1
 Home Assistant Supervisor: 2022.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:35:46] INFO: Pruning local files...
[15:35:46] INFO: Pruning local files finished
parse error: Unfinished string at EOF at line 2, column 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Config file of addon:

```
configuration_path: /share/rclone/rclone.conf
local_retention_days: 15
remotes:
  - name: NC Perso
    path: /Config_softs/HA/Auto/
    retention_days: 7
```

Rclone config file (generated using a local rclone on my computer and then copied on hassio system ! (sensible fields pruned ;)

```
[NC Perso]
type = webdav
url = https://mynextcloudserver/remote.php/dav
vendor = nextcloud
user = vincen
pass = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

Any ideas what's wrong there ?

Thanks

Vincèn

**Comment by alex3305** [comment]
Hi @vincegre,

Thanks for creating the time to create such an elaborate bug report. That is really appreciated! However I think this is a slight oversight by myself. I see that you have used a space in the name of your `rclone.conf`. Perhaps that should be an illegal character because of bash escaping 🤷.

Would you care to try without any spaces in the name, like this:

### Add-on configuration

```yaml
configuration_path: /share/rclone/rclone.conf
local_retention_days: 15
remotes:
  - name: NCPerso
    path: /Config_softs/HA/Auto/
    retention_days: 7
``` 

### `rclone.conf`

```ini
[NCPerso]
type = webdav
url = https://mynextcloudserver/remote.php/dav
vendor = nextcloud
user = vincen
pass = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

If this works (and I hope it does 🤞), you could also replace the space with an underscore or hyphen like so: `NC_Perso`.

Thanks! ❤️
