### ISSUE TITLE
Default Bitwarden server is not working anymore

### ISSUE THREAD

**Issue by ElVit** [alex3305/home-assistant-addons#37]
Hello @alex3305,

since some time my Bitwarden-Secrets-Addon does not working anymore. 
I use the default server in my configuration:
```
server: 'http://a0d7b954-bitwarden'
```

If I change the server to 
```
server: http://Home-Assistant-IP:Bitwarden-Port
```
then it's working again. 
Can you tell my maybe why the default address doesn't work anymore?

**Comment by alex3305** [comment]
Hi @ElVit,

Thanks for this feedback. I had noticed this too and thought it was because of my own configuration. Which I changed up quite a lot 🤷. It seems that I needed to add the Bitwarden port to get it working again:

```yaml
server: http://a0d7b954-bitwarden:7277/
username: homeassistant@localhost.lan
password: homeassistant
organization: Home Assistant
```

Can you verify that this is also working for you? Than I can change this in the default configuration and documentation.
